parameters:
    zim32_request_limit.class: Zim32\RequestLimitBundle\Lib\RequestLimit

services:
    zim32_request_limit:
        class: %zim32_request_limit.class%
        arguments: [@service_container]
        tags:
          - {name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 100}
